### ISSUE TITLE
Chemprop version incompatible in requirements.txt and setup.py

### ISSUE THREAD

**Issue by Stella-zjy** [swansonk14/SyntheMol#16]
The chemprop version stated in the requirements.txt is chemprop==1.5.2 while the one stated in the setup.py (or when you setup the environment using pip install synthemol) is chemprop 1.6.1. 

The two versions are not compatible with each other. Specifically, the model weights trained using chemprop 1.6.1 may not be applied to a model under chemprop 1.5.2. The following warning occurred when do so:
Warning: Pretrained parameter "readout.1.weight" cannot be found in model parameters.
Warning: Pretrained parameter "readout.1.bias" cannot be found in model parameters.
Warning: Pretrained parameter "readout.4.weight" cannot be found in model parameters.
Warning: Pretrained parameter "readout.4.bias" cannot be found in model parameters.

It will be helpful if you can update the requirements.txt file and change it into chemprop==1.6.1.
Thanks!

**Comment by swansonk14** [comment]
Hi @Stella-zjy,

Thank you for bringing up this issue! I mistakenly put Chemprop version 1.6.1 in the `setup.py` since I've recently been using that version in my other work, but I used version 1.5.2 to train the Chemprop models here. To resolve this, I changed the `setup.py` Chemprop version to 1.5.2 (as of SyntheMol version 1.0.4) to fix this. Please try uninstalling and reinstalling SyntheMol to see if that fixes the issue, and please let me know if you're still having any problems.

Best,
Kyle

**Comment by swansonk14** [comment]
Hi @Stella-zjy,

I'm going to close this issue, but please feel free to reopen it if you're still having issues.

Best,
Kyle
