### ISSUE TITLE
Issue Encountered While Replicating Results Using Chemprop Models

### ISSUE THREAD

**Issue by ylyzz21** [swansonk14/SyntheMol#21]
Hi Swanson,

I recently read your paper and attempted to utilize the tool in my project. However, I can't obtain the same output  while trying to reproduce the results from the paper using Chemprop models. Here's the workflow I followed:

1. I downloaded the models from [[this Zenodo record](https://zenodo.org/doi/10.5281/zenodo.10257838)](https://zenodo.org/doi/10.5281/zenodo.10257838) and copied the "antibiotic_chemprop/" folder to the "synthemol/models/" directory.
2. I then proceeded to run the script:
`synthemol     --model_path models/antibiotic_chemprop     --model_type chemprop     --save_dir generations/antibiotic_chemprop  --building_blocks_path models/antibiotic_chemprop/building_blocks.csv   --building_blocks_id_column  Reagent_ID   --building_blocks_score_column chemprop_ensemble_preds  --n_rollout 20000 --replicate`
3. I obtained the results located at generations/antibiotic_chemprop/:
- mcts_stats.csv
mcts_time,num_nonzero_reaction_molecules,approx_num_nodes_searched
0 days 07:06:56.485880,**25092**,**517249452**
These results differ from those presented in the paper and the data provided in [[this Zenodo record](https://zenodo.org/doi/10.5281/zenodo.10257838)](https://zenodo.org/doi/10.5281/zenodo.10257838), which are as follows:
num_rollouts,time,num_nodes,num_molecules
20000,0 days 08:26:58.217917,**452081984**,**24335**
Furthermore, upon comparing the molecules.csv 
[molecules.csv](https://github.com/user-attachments/files/17731781/molecules.csv)
[mcts_stats.csv](https://github.com/user-attachments/files/17731782/mcts_stats.csv)
in my dataset with the molecules.csv in the Data/6_generations_chemprop/ folder, I observed an overlap of only 1728 for the total dataset and 438 for the hits (score>=0.5) dataset.

Do you have any suggestions or insights on how to address this issue? Your assistance would be greatly appreciated.

Best regards,
Kaiyue

**Comment by swansonk14** [comment]
Hi @ylyzz21,

Thank you for raising this issue!

One possible problem could be that you didn't specify the `--reaction_to_building_blocks_path`, so SyntheMol defaults to a newer version of that file that might lead to slightly different results. I would recommend using the `Data/4_real_space/reaction_to_building_blocks_filtered.pkl` file from the Zenodo archive when specifying the `--reaction_to_building_blocks_path` since that's the one we used when running these experiments.

Another thing to check would the Python package versions you're using. Are you using the same versions as specified [here](https://github.com/swansonk14/SyntheMol/blob/main/requirements.txt)?

It is possible that even with the correct file and versions, you still might get slightly different results. There's some randomness in the algorithm that I've tried to control for, but even a slightly different result in one step of MCTS leads to a cascade of different molecules being generated. That said, you should still expect to see qualitatively similar results in terms of molecule quality, even if you don't get the exact same molecules that we generated.

If you look at the distribution of Chemprop antibiotic prediction scores or Tversky novelty values or Tanimoto diversity values, do they look similar to those in our paper? You can see instructions for running those calculations [here](https://github.com/swansonk14/SyntheMol/blob/main/docs/antibiotics.md#filter-generated-molecules) and for making plots [here](https://github.com/swansonk14/SyntheMol/blob/main/docs/plots.md) (although it's possible some of the plotting commands are out of date).

Best,
Kyle

**Comment by ylyzz21** [comment]
Hi Kyle,

Thank you for your thoughtful reply.

I have tried setting the `--reaction_to_building_blocks_path` to `Data/4_real_space/reaction_to_building_blocks_filtered.pkl` , and now the overlap between my dataset and  Data/6_generations_chemprop/  increased to **5190 (21%)** for the total dataset and **1106 (40%)** for the hits (score>=0.5) dataset.

I have also tried specifying the python package version as described in requirements.txt, but in practice, this has no effect on the results.
Although I cannot obtain exactly the same molecules as you, the distribution of antibiotic prediction scores is very similar. This is acceptable. Thanks again for answering this question.
![score_comparison](https://github.com/user-attachments/assets/42193a9f-62e9-45f0-9172-a72516e1a9a3)


Regards,
Kaiyue

**Comment by swansonk14** [comment]
Hi Kaiyue,

Thank you for trying that! I'm sorry the results are not perfectly reproducible (it's hard to guarantee exact reproducibility with these kinds of models), but I'm glad you were able to obtain qualitatively similar results! Please let me know if you run into any other issues with SyntheMol.

Best,
Kyle
